<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Http\Request;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $countries = [
            [
                "name_ar"                => "أفغانستان",
                "name_en"                => "AFGHANISTAN",
                "currency_name_ar"       => "أفغاني",
                "currency_name_en"       => "Afghani",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر آلاند",
                "name_en"                => "ÅLAND ISLANDS",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ألبانيا",
                "name_en"                => "ALBANIA",
                "currency_name_ar"       => "ليك",
                "currency_name_en"       => "Lek",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الجزائر",
                "name_en"                => "ALGERIA",
                "currency_name_ar"       => "دينار جزائري",
                "currency_name_en"       => "Algerian Dinar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ساموا الأمريكية",
                "name_en"                => "AMERICAN SAMOA",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أندورا",
                "name_en"                => "ANDORRA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أنجولا",
                "name_en"                => "ANGOLA",
                "currency_name_ar"       => "كوانزا",
                "currency_name_en"       => "Kwanza",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أنغويلا",
                "name_en"                => "ANGUILLA",
                "currency_name_ar"       => "دولار شرق الكاريبي",
                "currency_name_en"       => "East Caribbean Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "القارة القطبية الجنوبية",
                "name_en"                => "ANTARCTICA",
                "currency_name_ar"       => "لا يوجد عالمي",
                "currency_name_en"       => "No universal",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أنتيغوا وبربودا",
                "name_en"                => "ANTIGUA AND BARBUDA",
                "currency_name_ar"       => "دولار شرق الكاريبي",
                "currency_name_en"       => "East Caribbean Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الأرجنتين",
                "name_en"                => "ARGENTINA",
                "currency_name_ar"       => "بيزو أرجنتيني",
                "currency_name_en"       => "Argentine Peso",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أرمينيا",
                "name_en"                => "ARMENIA",
                "currency_name_ar"       => "درام أرميني",
                "currency_name_en"       => "Armenian Dram",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أروبا",
                "name_en"                => "ARUBA",
                "currency_name_ar"       => "فلورين أروبي",
                "currency_name_en"       => "Aruban Florin",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أستراليا",
                "name_en"                => "AUSTRALIA",
                "currency_name_ar"       => "دولار أسترالي",
                "currency_name_en"       => "Australian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "النمسا",
                "name_en"                => "AUSTRIA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أذربيجان",
                "name_en"                => "AZERBAIJAN",
                "currency_name_ar"       => "مانات أذربيجاني",
                "currency_name_en"       => "Azerbaijanian Manat",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر البهاما",
                "name_en"                => "BAHAMAS (THE)",
                "currency_name_ar"       => "دولار باهامي",
                "currency_name_en"       => "Bahamian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "البحرين",
                "name_en"                => "BAHRAIN",
                "currency_name_ar"       => "دينار بحريني",
                "currency_name_en"       => "Bahraini Dinar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بنغلاديش",
                "name_en"                => "BANGLADESH",
                "currency_name_ar"       => "تاكا",
                "currency_name_en"       => "Taka",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بربادوس",
                "name_en"                => "BARBADOS",
                "currency_name_ar"       => "دولار بربادوس",
                "currency_name_en"       => "Barbados Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بيلاروسيا",
                "name_en"                => "BELARUS",
                "currency_name_ar"       => "روبل بيلاروسي",
                "currency_name_en"       => "Belarussian Ruble",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بلجيكا",
                "name_en"                => "BELGIUM",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بليزي",
                "name_en"                => "BELIZE",
                "currency_name_ar"       => "دولار بليز",
                "currency_name_en"       => "Belize Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بنين",
                "name_en"                => "BENIN",
                "currency_name_ar"       => "فرنك وسط أفريقي BCEAO",
                "currency_name_en"       => "CFA Franc BCEAO",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "برمودا",
                "name_en"                => "BERMUDA",
                "currency_name_ar"       => "دولار برمودي",
                "currency_name_en"       => "Bermudian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بوتان",
                "name_en"                => "BHUTAN",
                "currency_name_ar"       => "نغولتروم",
                "currency_name_en"       => "Ngultrum",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بوتان",
                "name_en"                => "BHUTAN",
                "currency_name_ar"       => "روبية هندية",
                "currency_name_en"       => "Indian Rupee",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بوليفيا (دولة متعددة القوميات)",
                "name_en"                => "BOLIVIA (PLURINATIONAL STATE OF)",
                "currency_name_ar"       => "بوليفيانو",
                "currency_name_en"       => "Boliviano",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بوليفيا (دولة متعددة القوميات)",
                "name_en"                => "BOLIVIA (PLURINATIONAL STATE OF)",
                "currency_name_ar"       => "مفدول",
                "currency_name_en"       => "Mvdol",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بونير وسانت أوستاتيوس وسابا",
                "name_en"                => "BONAIRE, SINT EUSTATIUS AND SABA",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "البوسنة والهرسك",
                "name_en"                => "BOSNIA AND HERZEGOVINA",
                "currency_name_ar"       => "مارك قابل للتحويل",
                "currency_name_en"       => "Convertible Mark",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بوتسوانا",
                "name_en"                => "BOTSWANA",
                "currency_name_ar"       => "بولا",
                "currency_name_en"       => "Pula",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزيرة بوفيت",
                "name_en"                => "BOUVET ISLAND",
                "currency_name_ar"       => "كرونة نرويجية",
                "currency_name_en"       => "Norwegian Krone",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "البرازيل",
                "name_en"                => "BRAZIL",
                "currency_name_ar"       => "ريال برازيلي",
                "currency_name_en"       => "Brazilian Real",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "إقليم المحيط الهندي البريطاني",
                "name_en"                => "BRITISH INDIAN OCEAN TERRITORY (THE)",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بروناي دار السلام",
                "name_en"                => "BRUNEI DARUSSALAM",
                "currency_name_ar"       => "دولار بروناي",
                "currency_name_en"       => "Brunei Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بلغاريا",
                "name_en"                => "BULGARIA",
                "currency_name_ar"       => "ليف بلغاري",
                "currency_name_en"       => "Bulgarian Lev",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بوركينا فاسو",
                "name_en"                => "BURKINA FASO",
                "currency_name_ar"       => "فرنك وسط أفريقي BCEAO",
                "currency_name_en"       => "CFA Franc BCEAO",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بوروندي",
                "name_en"                => "BURUNDI",
                "currency_name_ar"       => "فرنك بوروندي",
                "currency_name_en"       => "Burundi Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الرأس الأخضر",
                "name_en"                => "CABO VERDE",
                "currency_name_ar"       => "إسكودو الرأس الأخضر",
                "currency_name_en"       => "Cabo Verde Escudo",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كمبوديا",
                "name_en"                => "CAMBODIA",
                "currency_name_ar"       => "ريال",
                "currency_name_en"       => "Riel",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الكاميرون",
                "name_en"                => "CAMEROON",
                "currency_name_ar"       => "فرنك وسط أفريقي BEAC",
                "currency_name_en"       => "CFA Franc BEAC",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كندا",
                "name_en"                => "CANADA",
                "currency_name_ar"       => "دولار كندي",
                "currency_name_en"       => "Canadian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر كايمان",
                "name_en"                => "CAYMAN ISLANDS (THE)",
                "currency_name_ar"       => "دولار جزر كايمان",
                "currency_name_en"       => "Cayman Islands Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جمهورية أفريقيا الوسطى",
                "name_en"                => "CENTRAL AFRICAN REPUBLIC (THE)",
                "currency_name_ar"       => "فرنك وسط أفريقي BEAC",
                "currency_name_en"       => "CFA Franc BEAC",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تشاد",
                "name_en"                => "CHAD",
                "currency_name_ar"       => "فرنك وسط أفريقي BEAC",
                "currency_name_en"       => "CFA Franc BEAC",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تشيلي",
                "name_en"                => "CHILE",
                "currency_name_ar"       => "وحدة فومينتو",
                "currency_name_en"       => "Unidad de Fomento",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "شيلي",
                "name_en"                => "CHILE",
                "currency_name_ar"       => "بيزو شيلي",
                "currency_name_en"       => "Chilean Peso",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الصين",
                "name_en"                => "CHINA",
                "currency_name_ar"       => "يوان رنمينبي",
                "currency_name_en"       => "Yuan Renminbi",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزيرة الكريسماس",
                "name_en"                => "CHRISTMAS ISLAND",
                "currency_name_ar"       => "دولار أسترالي",
                "currency_name_en"       => "Australian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر كوكوس",
                "name_en"                => "COCOS (KEELING) ISLANDS (THE)",
                "currency_name_ar"       => "دولار أسترالي",
                "currency_name_en"       => "Australian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كولومبيا",
                "name_en"                => "COLOMBIA",
                "currency_name_ar"       => "بيزو كولومبي",
                "currency_name_en"       => "Colombian Peso",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كولومبيا",
                "name_en"                => "COLOMBIA",
                "currency_name_ar"       => "وحدة قيمة الريال",
                "currency_name_en"       => "Unidad de Valor Real",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر القمر",
                "name_en"                => "COMOROS (THE)",
                "currency_name_ar"       => "فرنك القمري",
                "currency_name_en"       => "Comoro Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الكونغو (جمهورية الكونغو الديمقراطية)",
                "name_en"                => "CONGO (THE DEMOCRATIC REPUBLIC OF THE)",
                "currency_name_ar"       => "فرنك كونغولي",
                "currency_name_en"       => "Congolese Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الكونغو (جمهورية الكونغو الديمقراطية)",
                "name_en"                => "CONGO (THE)",
                "currency_name_ar"       => "فرنك وسط أفريقيا",
                "currency_name_en"       => "CFA Franc BEAC",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر كوك",
                "name_en"                => "COOK ISLANDS (THE)",
                "currency_name_ar"       => "دولار نيوزيلندي",
                "currency_name_en"       => "New Zealand Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كوستاريكا",
                "name_en"                => "COSTA RICA",
                "currency_name_ar"       => "كولون كوستاريكي",
                "currency_name_en"       => "Costa Rican Colon",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ساحل العاج",
                "name_en"                => "CÔTE D'IVOIRE",
                "currency_name_ar"       => "فرنك وسط أفريقيا",
                "currency_name_en"       => "CFA Franc BCEAO",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كرواتيا",
                "name_en"                => "CROATIA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كوبا",
                "name_en"                => "CUBA",
                "currency_name_ar"       => "بيزو قابل للتحويل",
                "currency_name_en"       => "Peso Convertible",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كوبا",
                "name_en"                => "CUBA",
                "currency_name_ar"       => "بيزو كوبي",
                "currency_name_en"       => "Cuban Peso",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كوراساو",
                "name_en"                => "CURAÇAO",
                "currency_name_ar"       => "جيلدر أنتيل هولندا",
                "currency_name_en"       => "Netherlands Antillean Guilder",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "قبرص",
                "name_en"                => "CYPRUS",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جمهورية التشيك",
                "name_en"                => "CZECH REPUBLIC (THE)",
                "currency_name_ar"       => "كورونا تشيكية",
                "currency_name_en"       => "Czech Koruna",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الدنمارك",
                "name_en"                => "DENMARK",
                "currency_name_ar"       => "كرونة دنماركية",
                "currency_name_en"       => "Danish Krone",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جيبوتي",
                "name_en"                => "DJIBOUTI",
                "currency_name_ar"       => "فرنك جيبوتي",
                "currency_name_en"       => "Djibouti Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "دومينيكا",
                "name_en"                => "DOMINICA",
                "currency_name_ar"       => "دولار شرق الكاريبي",
                "currency_name_en"       => "East Caribbean Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جمهورية الدومينيكان (THE)",
                "name_en"                => "DOMINICAN REPUBLIC (THE)",
                "currency_name_ar"       => "بيزو دومينيكا",
                "currency_name_en"       => "Dominican Peso",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الإكوادور",
                "name_en"                => "ECUADOR",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "مصر",
                "name_en"                => "EGYPT",
                "currency_name_ar"       => "جنيه مصري",
                "currency_name_en"       => "Egyptian Pound",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "السلفادور",
                "name_en"                => "EL SALVADOR",
                "currency_name_ar"       => "كولون السلفادور",
                "currency_name_en"       => "El Salvador Colon",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "السلفادور",
                "name_en"                => "EL SALVADOR",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غينيا الاستوائية",
                "name_en"                => "EQUATORIAL GUINEA",
                "currency_name_ar"       => "فرنك وسط أفريقيا",
                "currency_name_en"       => "CFA Franc BEAC",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "إريتريا",
                "name_en"                => "ERITREA",
                "currency_name_ar"       => "ناكفا",
                "currency_name_en"       => "Nakfa",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "إستونيا",
                "name_en"                => "ESTONIA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "إثيوبيا",
                "name_en"                => "ETHIOPIA",
                "currency_name_ar"       => "بير إثيوبي",
                "currency_name_en"       => "Ethiopian Birr",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الاتحاد الأوروبي",
                "name_en"                => "EUROPEAN UNION",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر فوكلاند (THE) [مالفيناس]",
                "name_en"                => "FALKLAND ISLANDS (THE) [MALVINAS]",
                "currency_name_ar"       => "جنيه جزر فوكلاند",
                "currency_name_en"       => "Falkland Islands Pound",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر فارو (THE)",
                "name_en"                => "FAROE ISLANDS (THE)",
                "currency_name_ar"       => "كرونة دنماركية",
                "currency_name_en"       => "Danish Krone",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "فيجي",
                "name_en"                => "FIJI",
                "currency_name_ar"       => "دولار فيجي",
                "currency_name_en"       => "Fiji Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "فنلندا",
                "name_en"                => "FINLAND",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "فرنسا",
                "name_en"                => "FRANCE",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غويانا الفرنسية",
                "name_en"                => "FRENCH GUIANA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بولينيزيا الفرنسية",
                "name_en"                => "FRENCH POLYNESIA",
                "currency_name_ar"       => "فرنك وسط أفريقيا",
                "currency_name_en"       => "CFP Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الأقاليم الجنوبية الفرنسية (THE)",
                "name_en"                => "FRENCH SOUTHERN TERRITORIES (THE)",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الجابون",
                "name_en"                => "GABON",
                "currency_name_ar"       => "فرنك وسط أفريقيا",
                "currency_name_en"       => "CFA Franc BEAC",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غامبيا (THE)",
                "name_en"                => "GAMBIA (THE)",
                "currency_name_ar"       => "دالاسي",
                "currency_name_en"       => "Dalasi",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جورجيا",
                "name_en"                => "GEORGIA",
                "currency_name_ar"       => "لاري",
                "currency_name_en"       => "Lari",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ألمانيا",
                "name_en"                => "GERMANY",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غانا",
                "name_en"                => "GHANA",
                "currency_name_ar"       => "سيدي غانا",
                "currency_name_en"       => "Ghana Cedi",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جبل طارق",
                "name_en"                => "GIBRALTAR",
                "currency_name_ar"       => "جنيه جبل طارق",
                "currency_name_en"       => "Gibraltar Pound",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "اليونان",
                "name_en"                => "GREECE",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جرينلاند",
                "name_en"                => "GREENLAND",
                "currency_name_ar"       => "كرونة دانمركية",
                "currency_name_en"       => "Danish Krone",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غرينادا",
                "name_en"                => "GRENADA",
                "currency_name_ar"       => "دولار شرق الكاريبي",
                "currency_name_en"       => "East Caribbean Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غوادلوب",
                "name_en"                => "GUADELOUPE",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غوام",
                "name_en"                => "GUAM",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غواتيمالا",
                "name_en"                => "GUATEMALA",
                "currency_name_ar"       => "كويتزال",
                "currency_name_en"       => "Quetzal",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غيرنسي",
                "name_en"                => "GUERNSEY",
                "currency_name_ar"       => "جنيه إسترليني",
                "currency_name_en"       => "Pound Sterling",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غينيا",
                "name_en"                => "GUINEA",
                "currency_name_ar"       => "فرنك غيني",
                "currency_name_en"       => "Guinea Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غينيا بيساو",
                "name_en"                => "GUINEA-BISSAU",
                "currency_name_ar"       => "فرنك وسط أفريقيا",
                "currency_name_en"       => "CFA Franc BCEAO",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "غيانا",
                "name_en"                => "GUYANA",
                "currency_name_ar"       => "دولار غيانا",
                "currency_name_en"       => "Guyana Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "هايتي",
                "name_en"                => "HAITI",
                "currency_name_ar"       => "جوردا",
                "currency_name_en"       => "Gourde",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "هايتي",
                "name_en"                => "HAITI",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر هيرد وماكدونالد",
                "name_en"                => "HEARD ISLAND AND McDONALD ISLANDS",
                "currency_name_ar"       => "دولار أسترالي",
                "currency_name_en"       => "Australian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الكرسي الرسولي (THE)",
                "name_en"                => "HOLY SEE (THE)",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "هندوراس",
                "name_en"                => "HONDURAS",
                "currency_name_ar"       => "لمبيرا",
                "currency_name_en"       => "Lempira",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "هونغ كونغ هونغ كونغ",
                "name_en"                => "HONG KONG",
                "currency_name_ar"       => "دولار هونج كونج",
                "currency_name_en"       => "Hong Kong Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "المجر",
                "name_en"                => "HUNGARY",
                "currency_name_ar"       => "فورنت",
                "currency_name_en"       => "Forint",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أيسلندا",
                "name_en"                => "ICELAND",
                "currency_name_ar"       => "كرونة أيسلندا",
                "currency_name_en"       => "Iceland Krona",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الهند",
                "name_en"                => "INDIA",
                "currency_name_ar"       => "روبية هندية",
                "currency_name_en"       => "Indian Rupee",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "إندونيسيا",
                "name_en"                => "INDONESIA",
                "currency_name_ar"       => "روبية",
                "currency_name_en"       => "Rupiah",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "صندوق النقد الدولي",
                "name_en"                => "INTERNATIONAL MONETARY FUND (IMF) ",
                "currency_name_ar"       => "حقوق السحب الخاصة",
                "currency_name_en"       => "SDR (Special Drawing Right)",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "إيران (الجمهورية الإسلامية)",
                "name_en"                => "IRAN (ISLAMIC REPUBLIC OF)",
                "currency_name_ar"       => "ريال إيراني",
                "currency_name_en"       => "Iranian Rial",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "العراق",
                "name_en"                => "IRAQ",
                "currency_name_ar"       => "دينار عراقي",
                "currency_name_en"       => "Iraqi Dinar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أيرلندا",
                "name_en"                => "IRELAND",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزيرة مان",
                "name_en"                => "ISLE OF MAN",
                "currency_name_ar"       => "جنيه إسترليني",
                "currency_name_en"       => "Pound Sterling",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "إسرائيل",
                "name_en"                => "ISRAEL",
                "currency_name_ar"       => "شيكل إسرائيلي جديد",
                "currency_name_en"       => "New Israeli Sheqel",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "إيطاليا",
                "name_en"                => "ITALY",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جامايكا",
                "name_en"                => "JAMAICA",
                "currency_name_ar"       => "دولار جامايكي",
                "currency_name_en"       => "Jamaican Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "اليابان",
                "name_en"                => "JAPAN",
                "currency_name_ar"       => "ين",
                "currency_name_en"       => "Yen",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جيرسي",
                "name_en"                => "JERSEY",
                "currency_name_ar"       => "جنيه إسترليني",
                "currency_name_en"       => "Pound Sterling",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الأردن",
                "name_en"                => "JORDAN",
                "currency_name_ar"       => "دينار أردني",
                "currency_name_en"       => "Jordanian Dinar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كازاخستان",
                "name_en"                => "KAZAKHSTAN",
                "currency_name_ar"       => "تينجي",
                "currency_name_en"       => "Tenge",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كينيا",
                "name_en"                => "KENYA",
                "currency_name_ar"       => "شلن كيني",
                "currency_name_en"       => "Kenyan Shilling",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كيريباتي",
                "name_en"                => "KIRIBATI",
                "currency_name_ar"       => "دولار أسترالي",
                "currency_name_en"       => "Australian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كوريا (جمهورية كوريا الشعبية الديمقراطية)",
                "name_en"                => "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)",
                "currency_name_ar"       => "وون كوري شمالي",
                "currency_name_en"       => "North Korean Won",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كوريا (جمهورية)",
                "name_en"                => "KOREA (THE REPUBLIC OF)",
                "currency_name_ar"       => "وون",
                "currency_name_en"       => "Won",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الكويت",
                "name_en"                => "KUWAIT",
                "currency_name_ar"       => "دينار كويتي",
                "currency_name_en"       => "Kuwaiti Dinar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "قيرغيزستان",
                "name_en"                => "KYRGYZSTAN",
                "currency_name_ar"       => "سوم",
                "currency_name_en"       => "Som",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جمهورية لاو الديمقراطية الشعبية",
                "name_en"                => "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)",
                "currency_name_ar"       => "كيب",
                "currency_name_en"       => "Kip",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "لاتفيا",
                "name_en"                => "LATVIA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "لبنان",
                "name_en"                => "LEBANON",
                "currency_name_ar"       => "جنيه لبناني",
                "currency_name_en"       => "Lebanese Pound",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ليسوتو",
                "name_en"                => "LESOTHO",
                "currency_name_ar"       => "لوتي",
                "currency_name_en"       => "Loti",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ليسوتو",
                "name_en"                => "LESOTHO",
                "currency_name_ar"       => "راند",
                "currency_name_en"       => "Rand",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ليبيريا",
                "name_en"                => "LIBERIA",
                "currency_name_ar"       => "دولار ليبيري",
                "currency_name_en"       => "Liberian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ليبيا",
                "name_en"                => "LIBYA",
                "currency_name_ar"       => "دينار ليبي",
                "currency_name_en"       => "Libyan Dinar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ليختنشتاين",
                "name_en"                => "LIECHTENSTEIN",
                "currency_name_ar"       => "فرنك سويسري",
                "currency_name_en"       => "Swiss Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ليتوانيا",
                "name_en"                => "LITHUANIA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "لوكسمبورج",
                "name_en"                => "LUXEMBOURG",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ماكاو",
                "name_en"                => "MACAO",
                "currency_name_ar"       => "باتاكا",
                "currency_name_en"       => "Pataca",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جمهورية مقدونيا الشمالية",
                "name_en"                => "REPUBLIC OF NORTH MACEDONIA",
                "currency_name_ar"       => "دينار",
                "currency_name_en"       => "Denar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "مدغشقر",
                "name_en"                => "MADAGASCAR",
                "currency_name_ar"       => "أرياري مدغشقري",
                "currency_name_en"       => "Malagasy Ariary",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ملاوي",
                "name_en"                => "MALAWI",
                "currency_name_ar"       => "كواشا",
                "currency_name_en"       => "Kwacha",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ماليزيا",
                "name_en"                => "MALAYSIA",
                "currency_name_ar"       => "رينغيت ماليزي",
                "currency_name_en"       => "Malaysian Ringgit",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر المالديف",
                "name_en"                => "MALDIVES",
                "currency_name_ar"       => "روفيا",
                "currency_name_en"       => "Rufiyaa",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "مالي",
                "name_en"                => "MALI",
                "currency_name_ar"       => "فرنك وسط أفريقيا BCEAO",
                "currency_name_en"       => "CFA Franc BCEAO",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "مالطا",
                "name_en"                => "MALTA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر مارشال",
                "name_en"                => "MARSHALL ISLANDS (THE)",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "مارتينيك",
                "name_en"                => "MARTINIQUE",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "موريتانيا",
                "name_en"                => "MAURITANIA",
                "currency_name_ar"       => "أوقية",
                "currency_name_en"       => "Ouguiya",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "موريشيوس",
                "name_en"                => "MAURITIUS",
                "currency_name_ar"       => "روبية موريشيوسية",
                "currency_name_en"       => "Mauritius Rupee",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "مايوت",
                "name_en"                => "MAYOTTE",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الدول الأعضاء في مجموعة البنك الأفريقي للتنمية",
                "name_en"                => "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP",
                "currency_name_ar"       => "وحدة حساب بنك التنمية الآسيوي",
                "currency_name_en"       => "ADB Unit of Account",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "المكسيك",
                "name_en"                => "MEXICO",
                "currency_name_ar"       => "بيزو مكسيكي",
                "currency_name_en"       => "Mexican Peso",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "المكسيك",
                "name_en"                => "MEXICO",
                "currency_name_ar"       => "وحدة تحويل العملات المكسيكية (UDI)",
                "currency_name_en"       => "Mexican Unidad de Inversion (UDI)",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ولايات ميكرونيزيا الموحدة",
                "name_en"                => "MICRONESIA (FEDERATED STATES OF)",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "مولدوفا (جمهورية)",
                "name_en"                => "MOLDOVA (THE REPUBLIC OF)",
                "currency_name_ar"       => "ليو مولدوفي",
                "currency_name_en"       => "Moldovan Leu",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "موناكو",
                "name_en"                => "MONACO",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "منغوليا",
                "name_en"                => "MONGOLIA",
                "currency_name_ar"       => "توغريك",
                "currency_name_en"       => "Tugrik",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الجبل الأسود",
                "name_en"                => "MONTENEGRO",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "مونتسيرات",
                "name_en"                => "MONTSERRAT",
                "currency_name_ar"       => "دولار شرق الكاريبي",
                "currency_name_en"       => "East Caribbean Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "المغرب",
                "name_en"                => "MOROCCO",
                "currency_name_ar"       => "درهم مغربي",
                "currency_name_en"       => "Moroccan Dirham",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "موزمبيق",
                "name_en"                => "MOZAMBIQUE",
                "currency_name_ar"       => "ميتيكال موزمبيقي",
                "currency_name_en"       => "Mozambique Metical",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ميانمار",
                "name_en"                => "MYANMAR",
                "currency_name_ar"       => "كيات",
                "currency_name_en"       => "Kyat",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ناميبيا",
                "name_en"                => "NAMIBIA",
                "currency_name_ar"       => "دولار نامبيا",
                "currency_name_en"       => "Namibia Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ناميبيا",
                "name_en"                => "NAMIBIA",
                "currency_name_ar"       => "راند",
                "currency_name_en"       => "Rand",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ناورو",
                "name_en"                => "NAURU",
                "currency_name_ar"       => "دولار أسترالي",
                "currency_name_en"       => "Australian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "نيبال",
                "name_en"                => "NEPAL",
                "currency_name_ar"       => "روبية نيبالية",
                "currency_name_en"       => "Nepalese Rupee",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "هولندا",
                "name_en"                => "NETHERLANDS (THE)",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "كاليدونيا الجديدة",
                "name_en"                => "NEW CALEDONIA",
                "currency_name_ar"       => "فرنك وسط أفريقيا BCEAO",
                "currency_name_en"       => "CFP Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "نيوزيلندا",
                "name_en"                => "NEW ZEALAND",
                "currency_name_ar"       => "دولار نيوزيلندي",
                "currency_name_en"       => "New Zealand Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "نيكاراغوا",
                "name_en"                => "NICARAGUA",
                "currency_name_ar"       => "كوردوبا أورو",
                "currency_name_en"       => "Cordoba Oro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "النيجر (THE)",
                "name_en"                => "NIGER (THE)",
                "currency_name_ar"       => "فرنك وسط أفريقيا BCEAO",
                "currency_name_en"       => "CFA Franc BCEAO",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "نيجيريا",
                "name_en"                => "NIGERIA",
                "currency_name_ar"       => "نايرا",
                "currency_name_en"       => "Naira",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "نيوي",
                "name_en"                => "NIUE",
                "currency_name_ar"       => "دولار نيوزيلندي",
                "currency_name_en"       => "New Zealand Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزيرة نورفولك",
                "name_en"                => "NORFOLK ISLAND",
                "currency_name_ar"       => "دولار أسترالي",
                "currency_name_en"       => "Australian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر ماريانا الشمالية (THE)",
                "name_en"                => "NORTHERN MARIANA ISLANDS (THE)",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "النرويج",
                "name_en"                => "NORWAY",
                "currency_name_ar"       => "كرونة نرويجية",
                "currency_name_en"       => "Norwegian Krone",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "عمان",
                "name_en"                => "OMAN",
                "currency_name_ar"       => "ريال عماني",
                "currency_name_en"       => "Rial Omani",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "باكستان",
                "name_en"                => "PAKISTAN",
                "currency_name_ar"       => "روبية باكستانية",
                "currency_name_en"       => "Pakistan Rupee",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بالاو",
                "name_en"                => "PALAU",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "فلسطين، دولة",
                "name_en"                => "PALESTINE, STATE OF",
                "currency_name_ar"       => "لا يوجد عملة عالمية",
                "currency_name_en"       => "No universal",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بنما",
                "name_en"                => "PANAMA",
                "currency_name_ar"       => "بالبوا",
                "currency_name_en"       => "Balboa",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بنما",
                "name_en"                => "PANAMA",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بابوا غينيا الجديدة",
                "name_en"                => "PAPUA NEW GUINEA",
                "currency_name_ar"       => "كينا",
                "currency_name_en"       => "Kina",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "باراغواي",
                "name_en"                => "PARAGUAY",
                "currency_name_ar"       => "غواراني",
                "currency_name_en"       => "Guarani",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بيرو",
                "name_en"                => "PERU",
                "currency_name_ar"       => "نويفو سول",
                "currency_name_en"       => "Nuevo Sol",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الفلبين (THE)",
                "name_en"                => "PHILIPPINES (THE)",
                "currency_name_ar"       => "بيزو فلبيني",
                "currency_name_en"       => "Philippine Peso",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بيتكيرن",
                "name_en"                => "PITCAIRN",
                "currency_name_ar"       => "دولار نيوزيلندي",
                "currency_name_en"       => "New Zealand Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بولندا",
                "name_en"                => "POLAND",
                "currency_name_ar"       => "زلوتي",
                "currency_name_en"       => "Zloty",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "البرتغال",
                "name_en"                => "PORTUGAL",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "بورتوريكو",
                "name_en"                => "PUERTO RICO",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "قطر",
                "name_en"                => "QATAR",
                "currency_name_ar"       => "ريال قطري",
                "currency_name_en"       => "Qatari Rial",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ريونيون",
                "name_en"                => "RÉUNION",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "رومانيا",
                "name_en"                => "ROMANIA",
                "currency_name_ar"       => "روماني ليو",
                "currency_name_en"       => "Romanian Leu",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الاتحاد الروسي (THE)",
                "name_en"                => "RUSSIAN FEDERATION (THE)",
                "currency_name_ar"       => "روبل روسي",
                "currency_name_en"       => "Russian Ruble",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "رواندا",
                "name_en"                => "RWANDA",
                "currency_name_ar"       => "فرنك رواندي",
                "currency_name_en"       => "Rwanda Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سان بارتيليمي",
                "name_en"                => "SAINT BARTHÉLEMY",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سانت هيلينا وأسينسيو وتريستان دا كونا",
                "name_en"                => "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
                "currency_name_ar"       => "جنيه سانت هيلينا",
                "currency_name_en"       => "Saint Helena Pound",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سانت كيتس ونيفيس",
                "name_en"                => "SAINT KITTS AND NEVIS",
                "currency_name_ar"       => "دولار شرق الكاريبي",
                "currency_name_en"       => "East Caribbean Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سانت لوسيا",
                "name_en"                => "SAINT LUCIA",
                "currency_name_ar"       => "دولار شرق الكاريبي",
                "currency_name_en"       => "East Caribbean Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سان مارتن (الجزء الفرنسي)",
                "name_en"                => "SAINT MARTIN (FRENCH PART)",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سان بيير وميكلون",
                "name_en"                => "SAINT PIERRE AND MIQUELON",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سانت فنسنت وجزر غرينادين",
                "name_en"                => "SAINT VINCENT AND THE GRENADINES",
                "currency_name_ar"       => "دولار شرق الكاريبي",
                "currency_name_en"       => "East Caribbean Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ساموا",
                "name_en"                => "SAMOA",
                "currency_name_ar"       => "تالا",
                "currency_name_en"       => "Tala",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سان مارينو",
                "name_en"                => "SAN MARINO",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ساو تومي وبرينسيبي",
                "name_en"                => "SAO TOME AND PRINCIPE",
                "currency_name_ar"       => "دوبرا",
                "currency_name_en"       => "Dobra",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "المملكة العربية السعودية",
                "name_en"                => "SAUDI ARABIA",
                "currency_name_ar"       => "ريال سعودي",
                "currency_name_en"       => "Saudi Riyal",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "السنغال",
                "name_en"                => "SENEGAL",
                "currency_name_ar"       => "فرنك وسط أفريقي BCEAO",
                "currency_name_en"       => "CFA Franc BCEAO",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "صربيا",
                "name_en"                => "SERBIA",
                "currency_name_ar"       => "دينار صربي",
                "currency_name_en"       => "Serbian Dinar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سيشيل",
                "name_en"                => "SEYCHELLES",
                "currency_name_ar"       => "روبية سيشل",
                "currency_name_en"       => "Seychelles Rupee",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سيراليون",
                "name_en"                => "SIERRA LEONE",
                "currency_name_ar"       => "ليون",
                "currency_name_en"       => "Leone",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سنغافورة",
                "name_en"                => "SINGAPORE",
                "currency_name_ar"       => "دولار سنغافوري",
                "currency_name_en"       => "Singapore Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سانت مارتن (الجزء الهولندي)",
                "name_en"                => "SINT MAARTEN (DUTCH PART)",
                "currency_name_ar"       => "جيلدر أنتيل الهولندي",
                "currency_name_en"       => "Netherlands Antillean Guilder",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "نظام التعويضات الإقليمي الموحد لجزر باغوسو",
                "name_en"                => "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS 'SUCRE'",
                "currency_name_ar"       => "سوكري",
                "currency_name_en"       => "Sucre",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سلوفاكيا",
                "name_en"                => "SLOVAKIA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سلوفينيا",
                "name_en"                => "SLOVENIA",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر سليمان",
                "name_en"                => "SOLOMON ISLANDS",
                "currency_name_ar"       => "دولار جزر سليمان",
                "currency_name_en"       => "Solomon Islands Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الصومال",
                "name_en"                => "SOMALIA",
                "currency_name_ar"       => "شلن صومالي",
                "currency_name_en"       => "Somali Shilling",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جنوب أفريقيا",
                "name_en"                => "SOUTH AFRICA",
                "currency_name_ar"       => "راند",
                "currency_name_en"       => "Rand",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
                "name_en"                => "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
                "currency_name_ar"       => "غير عالمي",
                "currency_name_en"       => "No universal",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جنوب السودان",
                "name_en"                => "SOUTH SUDAN",
                "currency_name_ar"       => "جنيه جنوب السودان",
                "currency_name_en"       => "South Sudanese Pound",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "إسبانيا",
                "name_en"                => "SPAIN",
                "currency_name_ar"       => "يورو",
                "currency_name_en"       => "Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سريلانكا",
                "name_en"                => "SRI LANKA",
                "currency_name_ar"       => "روبية سريلانكا",
                "currency_name_en"       => "Sri Lanka Rupee",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "السودان",
                "name_en"                => "SUDAN (THE)",
                "currency_name_ar"       => "جنيه سوداني",
                "currency_name_en"       => "Sudanese Pound",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سورينام",
                "name_en"                => "SURINAME",
                "currency_name_ar"       => "دولار سورينام",
                "currency_name_en"       => "Surinam Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سفالبارد وجان ماين",
                "name_en"                => "SVALBARD AND JAN MAYEN",
                "currency_name_ar"       => "كرونة نرويجية",
                "currency_name_en"       => "Norwegian Krone",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سوازيلاند",
                "name_en"                => "SWAZILAND",
                "currency_name_ar"       => "ليلانجيني",
                "currency_name_en"       => "Lilangeni",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "السويد",
                "name_en"                => "SWEDEN",
                "currency_name_ar"       => "كرونة سويدية",
                "currency_name_en"       => "Swedish Krona",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سويسرا",
                "name_en"                => "SWITZERLAND",
                "currency_name_ar"       => "يورو WIR",
                "currency_name_en"       => "WIR Euro",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "سويسرا",
                "name_en"                => "SWITZERLAND",
                "currency_name_ar"       => "فرنك سويسري",
                "currency_name_en"       => "Swiss Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الجمهورية العربية السورية",
                "name_en"                => "SWITZERLAND",
                "currency_name_ar"       => "فرنك WIR",
                "currency_name_en"       => "WIR Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تايوان (مقاطعة صينية)",
                "name_en"                => "SYRIAN ARAB REPUBLIC",
                "currency_name_ar"       => "جنيه سوري",
                "currency_name_en"       => "Syrian Pound",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "طاجيكستان",
                "name_en"                => "TAIWAN (PROVINCE OF CHINA)",
                "currency_name_ar"       => "دولار تايواني جديد",
                "currency_name_en"       => "New Taiwan Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تنزانيا، جمهورية",
                "name_en"                => "TAJIKISTAN",
                "currency_name_ar"       => "سوموني",
                "currency_name_en"       => "Somoni",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "المتحدة",
                "name_en"                => "TANZANIA, UNITED REPUBLIC OF",
                "currency_name_ar"       => "شلن تنزاني",
                "currency_name_en"       => "Tanzanian Shilling",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تايلاند",
                "name_en"                => "THAILAND",
                "currency_name_ar"       => "بات",
                "currency_name_en"       => "Baht",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تيمور الشرقية",
                "name_en"                => "TIMOR-LESTE",
                "currency_name_ar"       => "دولار أمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "توغو",
                "name_en"                => "TOGO",
                "currency_name_ar"       => "فرنك وسط أفريقي BCEAO",
                "currency_name_en"       => "CFA Franc BCEAO",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "توكيلاو",
                "name_en"                => "TOKELAU",
                "currency_name_ar"       => "دولار نيوزيلندي",
                "currency_name_en"       => "New Zealand Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تونغا",
                "name_en"                => "TONGA",
                "currency_name_ar"       => "بانجا",
                "currency_name_en"       => "Pa’anga",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "ترينيداد وتوباغو",
                "name_en"                => "TRINIDAD AND TOBAGO",
                "currency_name_ar"       => "دولار ترينيداد وتوباغو",
                "currency_name_en"       => "Trinidad and Tobago Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تونس",
                "name_en"                => "TUNISIA",
                "currency_name_ar"       => "تونسي الدينار",
                "currency_name_en"       => "Tunisian Dinar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تركيا",
                "name_en"                => "TURKEY",
                "currency_name_ar"       => "الليرة التركية",
                "currency_name_en"       => "Turkish Lira",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "تركمانستان",
                "name_en"                => "TURKMENISTAN",
                "currency_name_ar"       => "مانات تركمانستان الجديدة",
                "currency_name_en"       => "Turkmenistan New Manat",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر توركس وكايكوس",
                "name_en"                => "TURKS AND CAICOS ISLANDS (THE)",
                "currency_name_ar"       => "الدولار الأمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "توفالو",
                "name_en"                => "TUVALU",
                "currency_name_ar"       => "الدولار الأسترالي",
                "currency_name_en"       => "Australian Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أوغندا",
                "name_en"                => "UGANDA",
                "currency_name_ar"       => "شلن أوغندي",
                "currency_name_en"       => "Uganda Shilling",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أوكرانيا",
                "name_en"                => "UKRAINE",
                "currency_name_ar"       => "هريفنيا",
                "currency_name_en"       => "Hryvnia",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الإمارات العربية المتحدة",
                "name_en"                => "UNITED ARAB EMIRATES (THE)",
                "currency_name_ar"       => "الدرهم الإماراتي",
                "currency_name_en"       => "UAE Dirham",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "المملكة المتحدة لبريطانيا العظمى وأيرلندا الشمالية",
                "name_en"                => "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)",
                "currency_name_ar"       => "الجنيه الإسترليني",
                "currency_name_en"       => "Pound Sterling",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر الولايات المتحدة الصغيرة النائية",
                "name_en"                => "UNITED STATES MINOR OUTLYING ISLANDS (THE)",
                "currency_name_ar"       => "الدولار الأمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الولايات المتحدة الأمريكية",
                "name_en"                => "UNITED STATES OF AMERICA (THE)",
                "currency_name_ar"       => "الدولار الأمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الولايات المتحدة الأمريكية",
                "name_en"                => "UNITED STATES OF AMERICA (THE)",
                "currency_name_ar"       => "الدولار الأمريكي (اليوم التالي)",
                "currency_name_en"       => "US Dollar (Next day)",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أوروغواي",
                "name_en"                => "URUGUAY",
                "currency_name_ar"       => "البيزو الأوروغواياني بالعملة الموحدة (URUIURUI)",
                "currency_name_en"       => "Uruguay Peso en Unidades Indexadas (URUIURUI)",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أوروغواي",
                "name_en"                => "URUGUAY",
                "currency_name_ar"       => "البيزو الأوروغواياني",
                "currency_name_en"       => "Peso Uruguayo",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "أوزبكستان",
                "name_en"                => "UZBEKISTAN",
                "currency_name_ar"       => "السوم الأوزبكي",
                "currency_name_en"       => "Uzbekistan Sum",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "فانواتو",
                "name_en"                => "VANUATU",
                "currency_name_ar"       => "فاتو",
                "currency_name_en"       => "Vatu",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "فنزويلا (جمهورية البوليفارية)",
                "name_en"                => "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
                "currency_name_ar"       => "بوليفار",
                "currency_name_en"       => "Bolivar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "فنزويلا (جمهورية البوليفارية)",
                "name_en"                => "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
                "currency_name_ar"       => "بوليفار",
                "currency_name_en"       => "Bolivar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "فيتنام",
                "name_en"                => "VIET NAM",
                "currency_name_ar"       => "دونغ",
                "currency_name_en"       => "Dong",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "فيرجين الجزر (البريطانية)",
                "name_en"                => "VIRGIN ISLANDS (BRITISH)",
                "currency_name_ar"       => "الدولار الأمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "جزر فيرجن (الأمريكية)",
                "name_en"                => "VIRGIN ISLANDS (U.S.)",
                "currency_name_ar"       => "الدولار الأمريكي",
                "currency_name_en"       => "US Dollar",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "واليس وفوتونا",
                "name_en"                => "WALLIS AND FUTUNA",
                "currency_name_ar"       => "الفرنك الكاريبي الموحد",
                "currency_name_en"       => "CFP Franc",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "الصحراء الغربية",
                "name_en"                => "WESTERN SAHARA",
                "currency_name_ar"       => "الدرهم المغربي",
                "currency_name_en"       => "Moroccan Dirham",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "اليمن",
                "name_en"                => "YEMEN",
                "currency_name_ar"       => "الريال اليمني",
                "currency_name_en"       => "Yemeni Rial",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "زامبيا",
                "name_en"                => "ZAMBIA",
                "currency_name_ar"       => "الكواشا الزامبية",
                "currency_name_en"       => "Zambian Kwacha",
                "currency_exchange_rate" => 1,
            ],
            [
                "name_ar"                => "زيمبابوي",
                "name_en"                => "ZIMBABWE",
                "currency_name_ar"       => "الدولار الزيمبابوي",
                "currency_name_en"       => "Zimbabwe Dollar",
                "currency_exchange_rate" => 1,
            ],
        ];

        foreach ($countries as $country) {
            $is_found = Category::where('parent', 'countries')->whereHas('translations' , function($trans) use($country){
                $trans->where('name' , $country['name_ar']);
            })->exists();
            if (!$is_found) {
                $value = Category::select('id', 'key', 'parent', 'value')->where('parent', 'countries')->withTrashed()->max('value');
                $request = [
                    'parent'                 => 'countries',
                    'value'                  => $value + 1,
                    'currency_exchange_rate' => 1,
                ];

                $country_request = new Request($country);

                Category::updateOrCreate(['id' => 0], $request)->createTranslation($country_request);
            }
        }

        info('Done Successfully');
        return "Done";
    }
}
